### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WP_Rocket\Engine\Preload\Subscriber::remove_private_post() must be of the type string, null given

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-rocket#1]
```
[25-Oct-2023 13:01:01 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WP_Rocket\Engine\Preload\Subscriber::remove_private_post() must be of the type string, null given, called in /home/customer/www/example.com/public_html/wp-includes/class-wp-hook.php on line 310 and defined in /home/customer/www/example.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Preload/Subscriber.php:467
Stack trace:
#0 /home/customer/www/example.com/public_html/wp-includes/class-wp-hook.php(310): WP_Rocket\Engine\Preload\Subscriber->remove_private_post(NULL, 'subscr_pending', Object(WP_Post))
#1 /home/customer/www/example.com/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(false, Array)
#2 /home/customer/www/example.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/customer/www/example.com/public_html/wp-includes/post.php(5383): do_action('transition_post...', NULL, 'subscr_pending', Object(WP_Post))
#4 /home/customer/www/example.com/public_html/wp-includes/post.php(4643): wp_transition_post_status(NULL, 'subscr_pend in /home/customer/www/example.com/public_html/wp-content/plugins/wp-rocket/inc/Engine/Preload/Subscriber.php on line 467
```

https://github.com/pronamic/wp-rocket/blob/8ca54aee87013b3201121da98cdcd8a5dc3eccf9/inc/Engine/Preload/Subscriber.php#L128

https://github.com/pronamic/wp-rocket/blob/8ca54aee87013b3201121da98cdcd8a5dc3eccf9/inc/Engine/Preload/Subscriber.php#L459-L478

According to https://developer.wordpress.org/reference/hooks/transition_post_status/ it should be a `string`, but it is not yet clear why `null` is passed.

```
#4 /home/customer/www/example.com/public_html/wp-includes/post.php(4643): wp_transition_post_status(NULL, 'subscr_pend in /home/customer/www/example.com/public_html/wp-content/plugins/wp-
```

https://github.com/WordPress/WordPress/blob/6.3.2/wp-includes/post.php#L4643

```
#3 /home/customer/www/example.com/public_html/wp-includes/post.php(5383): do_action('transition_post...', NULL, 'subscr_pending', Object(WP_Post))
```

https://github.com/WordPress/WordPress/blob/6.3.2/wp-includes/post.php#L5383

**Comment by remcotolsma** [comment]
Solved: https://github.com/pronamic/wp-pay-core/issues/158#issuecomment-1782732500.
